context:
  version: 1.4.2

package:
  name: purs-backend-es
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/purs-backend-es/-/purs-backend-es-${{ version }}.tgz
  sha256: a0490052aed5173da0079af5db8b2cbb81ffceeda0eb276b02b577373e7ce03a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - purs-backend-es --help

about:
  license: MIT
  license_file: LICENSE
  summary: Optimizing backend toolkit and modern ECMAScript backend for PureScript
  homepage: https://github.com/aristanetworks/purescript-backend-optimizer
  repository: https://github.com/aristanetworks/purescript-backend-optimizer

extra:
  recipe-maintainers:
    - danielnachun
